name: Build and Deploy to Azure Web App (Self-Hosted)

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**'
      - '.github/workflows/deploy-self-hosted.yml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - '**'
      - '.github/workflows/deploy-self-hosted.yml'

env:
  AZURE_WEBAPP_NAME: ${{ secrets.WEBAPP_NAME }}
  CONTAINER_REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract commit info
      id: commit
      run: |
        echo "short_sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    # Buildxセットアップはスキップ（Podmanでは不要）
    
    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | podman login \
          ${{ secrets.ACR_LOGIN_SERVER }} \
          -u ${{ secrets.ACR_USERNAME }} \
          --password-stdin

    - name: Generate image tags
      id: tags
      run: |
        COMMIT_TAG="${{ steps.commit.outputs.short_sha }}"
        BRANCH_TAG="${{ steps.commit.outputs.branch }}-${{ steps.commit.outputs.short_sha }}"
        TIMESTAMP_TAG="${{ steps.commit.outputs.timestamp }}-${{ steps.commit.outputs.short_sha }}"
        
        TAGS="${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${COMMIT_TAG}"
        TAGS="${TAGS},${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${BRANCH_TAG}"
        TAGS="${TAGS},${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${TIMESTAMP_TAG}"
        
        # メインブランチの場合はlatestタグも追加
        if [[ "${{ steps.commit.outputs.branch }}" == "main" || "${{ steps.commit.outputs.branch }}" == "master" ]]; then
          TAGS="${TAGS},${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:latest"
        fi
        
        echo "tags=${TAGS}" >> $GITHUB_OUTPUT
        echo "commit_tag=${COMMIT_TAG}" >> $GITHUB_OUTPUT
        
        echo "Generated tags:"
        echo "${TAGS}" | tr ',' '\n'

    - name: Build Docker image
      run: |
        podman build \
          -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ steps.tags.outputs.commit_tag }} \
          -f ./Dockerfile \
          .
    
    - name: Tag additional versions
      run: |
        # メインブランチの場合はlatestタグも追加
        if [[ "${{ steps.commit.outputs.branch }}" == "main" || "${{ steps.commit.outputs.branch }}" == "master" ]]; then
          podman tag \
            ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ steps.tags.outputs.commit_tag }} \
            ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:latest
        fi
        
        # ブランチタグを追加
        podman tag \
          ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ steps.tags.outputs.commit_tag }} \
          ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ steps.commit.outputs.branch }}-${{ steps.commit.outputs.short_sha }}
    
    - name: Push all tags to ACR
      run: |
        # コミットタグをプッシュ
        podman push ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ steps.tags.outputs.commit_tag }}
        
        # ブランチタグをプッシュ
        podman push ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ steps.commit.outputs.branch }}-${{ steps.commit.outputs.short_sha }}
        
        # メインブランチの場合はlatestもプッシュ
        if [[ "${{ steps.commit.outputs.branch }}" == "main" || "${{ steps.commit.outputs.branch }}" == "master" ]]; then
          podman push ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:latest
        fi

    - name: Log in to Azure
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }

    - name: Deploy to Azure Web App
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.WEBAPP_NAME }}
        images: ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ steps.tags.outputs.commit_tag }}

    - name: Azure logout
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: az logout
      continue-on-error: true