name: Build and Deploy to Azure Web App (Self-Hosted with Docker)

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**'
      - '.github/workflows/deploy-self-hosted.yml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - '**'
      - '.github/workflows/deploy-self-hosted.yml'

env:
  AZURE_WEBAPP_NAME: ${{ secrets.WEBAPP_NAME }}
  CONTAINER_REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    outputs:
      image-tag: ${{ steps.tags.outputs.commit_tag }}
      app-url: ${{ steps.deploy-info.outputs.app-url }}
      deployment-status: ${{ steps.deploy.outcome }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract commit info
      id: commit
      run: |
        echo "short_sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.commit.outputs.short_sha }}
          ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Log in to Azure
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Verify Azure account context
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        echo "Verifying Azure account context..."
        az account show --output table
        
        echo "Checking subscription ID..."
        CURRENT_SUB=$(az account show --query id -o tsv)
        EXPECTED_SUB="${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        
        if [ "$CURRENT_SUB" != "$EXPECTED_SUB" ]; then
          echo "❌ Error: Wrong subscription active"
          echo "Expected: $EXPECTED_SUB"
          echo "Current:  $CURRENT_SUB"
          exit 1
        fi
        
        echo "✅ Verified: Correct subscription is active"
        echo "Tenant: $(az account show --query tenantId -o tsv)"
        echo "Subscription: $(az account show --query name -o tsv)"

    - name: Deploy to Azure Web App
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      id: deploy
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.WEBAPP_NAME }}
        images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.commit.outputs.short_sha }}

    - name: Verify deployment
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      id: deploy-info
      run: |
        echo "🔍 Verifying deployment to Azure Web App..."
        APP_NAME="${{ secrets.WEBAPP_NAME }}"
        
        # Get app details
        echo "📋 Getting app information..."
        az webapp show --name "$APP_NAME" --resource-group "$(az webapp list --query "[?name=='$APP_NAME'].resourceGroup" -o tsv)" --query "{name:name,state:state,defaultHostName:defaultHostName}" -o table
        
        # Check if the deployment was successful
        APP_STATE=$(az webapp show --name "$APP_NAME" --resource-group "$(az webapp list --query "[?name=='$APP_NAME'].resourceGroup" -o tsv)" --query "state" -o tsv)
        
        if [ "$APP_STATE" = "Running" ]; then
          echo "✅ Web App is running successfully"
          APP_URL="https://$(az webapp show --name "$APP_NAME" --resource-group "$(az webapp list --query "[?name=='$APP_NAME'].resourceGroup" -o tsv)" --query "defaultHostName" -o tsv)"
          echo "🌐 Application URL: $APP_URL"
          echo "app-url=$APP_URL" >> $GITHUB_OUTPUT
        else
          echo "❌ Web App is not in running state: $APP_STATE"
          exit 1
        fi
        
        echo "✅ Deployment verification completed"

    - name: Azure logout
      if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      run: |
        echo "Logging out from Azure..."
        az logout || echo "Logout failed or already logged out"
        echo "Azure logout completed"